Def tel class
JASMINE-Mission/telescope_baseline pull request #10
Opened 2022-05-09 05:36 UTC by kataza

中心推定精度の計算プログラムの見直しをしています。まずは、最も下位レベルのところで、各種の波長依存性のあるパラメータを扱うクラスとして WlEfic  を作成しました。これで 望遠鏡効率、バンドパスフィルター効率、さらに、検出器量子効率を同じように扱うつもりです。　
src/telescope_baseline/dataclass/wl_eff.py　WlEficを定義するコード
src/telescope_baseline/utils/plot_eff.py         WlEfic を用いて、データをプロットするユーティリティ
tests/dataclass/wl_eff_test.py                        WlEficのテスト
src/telescope_baseline/data/teleff.json        望遠鏡の効率(フィルター無し、保護コートなし)
src/telescope_baseline/data/teleffp.json      望遠鏡の効率(フィルター無し、保護コートあり)
src/telescope_baseline/data/filter/filter*.json  フィルターの効率、短波長側のcut-on波長を何通りか
src/telescope_baseline/data/qe/qe*.json      検出器量子効率、温度を何通りか

2022-05-09 06:20 UTC, yamadayy commented
PEP8違反の変数名がいくつかあるのですが(大文字から始まっている)、変数名を変更してもよいのでしょうか？

mapsim1.pyの22行目、argsが定義されていない警告が出ます。if __name__ =- '__main__'のifの中にどこまでが入る想定でしょう？文法的には直後の1行だけがifの中にあり、ifが呼ばれない状況では未定義のargsが現れます。下をいれてまずいのであれば、ifの前にダミーでargsを定義するのでしょうか？

2022-05-09 06:43 UTC, kataza commented
mapsim1.pyですが、docoptを呼ぶときにいつも同じようにしていました。ifの中で args から適当な変数へ代入すること、およびifが満たされないときに変数のdefaultを定義しておくことが必要ですね。

2022-05-10 06:18 UTC, yamadayy approved these changes

2022-05-10 07:15 UTC, tkamizuka commented on src/telescope_baseline/dataclass/wl_eff.py
> +class WlEfic:
Efic だと意味をくみ取るのが難しいと思いました。WlEff か WlEffic か WlEfficiency とかであれば分かりやすい気がしますがいかがでしょうか。

現状 dataclass/wl_eff.py の WlEfic クラスの定義となっていますが、定義しているのは efficiency の dataclass なので dataclass/efficiency.py に Efficiency クラスを定義する、というような命名にしたほうが分かりよいかなと思いました。dataclass/efficiency.py に QuantumEfficiency, OpticsEfficiency といった class が定義されているとかでもいいかなと思いましたが…好みの問題かもしれません。

2022-05-10 07:15 UTC, tkamizuka commented on src/telescope_baseline/dataclass/wl_eff.py
> +        title (str): Title of the data
l. 11, 12 に合わせるなら l 13, 14 末尾にもピリオドでしょうか。

2022-05-10 07:21 UTC, xr0038 commented on src/telescope_baseline/dataclass/wl_eff.py
> +class WlEfic:
個人的には名前はケチらずに書き下す方に一票です．

wavelength 要素を入れようとすると単語の選択が厳しいですが…… wavelength-domain の efficiency しか使わないと思うと上塚さんの提案した方針の方がスッキリしそうですね．

2022-05-10 07:44 UTC, xr0038 commented
とりあえず `pytest` が通りませんでした．
`data` に追加したファイルを `MANIFEST.in` に記載する必要があるでしょうか？

2022-05-10 07:45 UTC, xr0038 requested changes
とりいそぎ `MANIFEST.in` の設定の確認をお願いします．

2022-05-10 07:45 UTC, xr0038 commented on src/telescope_baseline/dataclass/__init__.py
> +__description__ = ''
`dataclass` だけ別にバージョン番号をつける意図がなければ，ここに `__version__` や `__author__`は書かないほうがコードの保守が楽になると思います．

2022-05-10 07:45 UTC, xr0038 commented on src/telescope_baseline/utils/__init__.py
> +__description__ = ''
`dataclass` の `__init__.py` と同様です．

2022-05-10 07:45 UTC, xr0038 commented on tests/dataclass/wl_eff_test.py
> +    assert wl_eff.wavelength[10] == 0.51
浮動小数点と `==` で比較するときには `approx` を使うことをおすすめします．

- https://docs.pytest.org/en/6.2.x/reference.html#pytest-approx

2022-05-10 07:45 UTC, xr0038 commented on src/telescope_baseline/utils/plot_eff.py
> +fig.savefig(args['-p'],transparent=True)
ここもインデントするべきでしょうか？

2022-05-10 09:41 UTC, xr0038 commented
`dataclass` のテストが通ることを確認しました．

2022-05-11 12:43 UTC, HajimeKawahara commented on tests/dataclass/wl_eff_test.py
> +    assert wl_eff.efficiency[10] == 0.023012329078860527
```python
assert wl_eff.efficiency[10] == pytest.approx(0.023012329078860527)
```
ですかね

2022-05-11 23:13 UTC, HajimeKawahara commented on src/telescope_baseline/dataclass/wl_eff.py
> +class WlEfic:
I propose the name change, for instance, `wavelenght_efficiency`.

2022-05-11 23:14 UTC, HajimeKawahara approved these changes
Thank you! The test worked in my environment.

2022-05-16 04:41 UTC, kataza commented on src/telescope_baseline/data/filter/filter090.json
> +  "comment": "0.0005 + 0.9975/(1+np.exp( (wls - W)/dwl ))",
titleとcommentの内容をまるっと変えました。生成スクリプト make_filter.py 追加しました。

2022-05-16 04:41 UTC, kataza commented on src/telescope_baseline/data/filter/filter095.json
> +  "comment": "0.0005 + 0.9975/(1+np.exp( (wls - W)/dwl ))",
titleとcommentの内容をまるっと変えました。生成スクリプト make_filter.py 追加しました。

2022-05-16 04:41 UTC, kataza commented on src/telescope_baseline/data/filter/filter100.json
> +  "comment": "0.0005 + 0.9975/(1+np.exp( (wls - W)/dwl ))",
titleとcommentの内容をまるっと変えました。生成スクリプト make_filter.py 追加しました。

2022-05-16 04:42 UTC, kataza commented on src/telescope_baseline/data/filter/filter105.json
> +  "comment": "0.0005 + 0.9975/(1+np.exp( (wls - W)/dwl ))",
titleとcommentの内容をまるっと変えました。生成スクリプト make_filter.py 追加しました。

2022-05-16 04:42 UTC, kataza commented on src/telescope_baseline/data/filter/filter110.json
> +  "comment": "0.0005 + 0.9975/(1+np.exp( (wls - W)/dwl ))",
titleとcommentの内容をまるっと変えました。生成スクリプト make_filter.py 追加しました。

2022-05-16 04:42 UTC, kataza commented on src/telescope_baseline/data/filter/filter115.json
> +  "comment": "0.0005 + 0.9975/(1+np.exp( (wls - W)/dwl ))",
titleとcommentの内容をまるっと変えました。生成スクリプト make_filter.py 追加しました。

2022-05-16 04:48 UTC, tkamizuka commented
フィルタの json ファイルの修正が反映されていないかもしれません(?)。最後のコミットには make_filter.py の追加のみが add されているように見えます。 @kataza

2022-05-17 00:36 UTC, kataza commented on src/telescope_baseline/data/teleff.json
> +  "comment": "R from Thorlabs_Unprotected_Gold_CoatingM03.xlsx, p-polarized  and Eff=(0.99R)^5",
titleとcommentの内容をまるっと変えました。

2022-05-17 00:37 UTC, kataza commented on src/telescope_baseline/data/teleffp.json
> +  "comment": "R from Thorlabs_Protected_Gold_Coating.xlsx, p-polarized  and Eff=(0.99R)^5",
こちらは廃止したいと思います。どうすればいいのかわからないど。

2022-05-17 00:40 UTC, xr0038 commented
対応が完了したコメントは "Resolve conversation" を押していってください．

2022-05-17 22:57 UTC, kataza commented on src/telescope_baseline/dataclass/wl_eff.py
> +class WlEfic:
efficiency.py の Efficiency クラスに変更しました

2022-05-17 22:57 UTC, kataza commented on src/telescope_baseline/dataclass/__init__.py
> +__description__ = ''
version, author の行を抜きました

2022-05-17 22:59 UTC, kataza commented on src/telescope_baseline/utils/__init__.py
> +__description__ = ''
versionとauthor をぬきました

2022-05-17 22:59 UTC, kataza commented on tests/dataclass/wl_eff_test.py
> +    assert wl_eff.wavelength[10] == 0.51
はい、approxを使いました

2022-05-17 23:01 UTC, kataza commented on src/telescope_baseline/utils/plot_eff.py
> +fig.savefig(args['-p'],transparent=True)
インデントしました。この手の、コマンドラインから呼び出すことがそもそも前提になっているコードのスタイルってどうするのが恰好いいのでしょうかね？インデントが深くなるのは嫌いなのだけど。。

2022-05-17 23:04 UTC, kataza commented on src/telescope_baseline/dataclass/wl_eff.py
> +class WlEfic:
上塚さんの提案にしたがって、efficiency にしました。wavelength をいれたほうがよいかな、それだと長くなりすぎるかな、と迷っています。

2022-05-18 00:06 UTC, tkamizuka commented on src/telescope_baseline/dataclass/wl_eff.py
> +class WlEfic:
このクラスが wavelength という attribute を保持するので、わざわざ class の名前に wavelength をいれなくても良いのではないかと思いました。もし気持ち悪ければ frequency も作って c/wavelength になるように仕込んでおく手もあるかもしれませんが…そこまでしなくてもとも思います。

2022-05-18 00:20 UTC, xr0038 commented on src/telescope_baseline/utils/plot_eff.py
> +fig.savefig(args['-p'],transparent=True)
> インデントが深くなるのは嫌い

原則として同意します……．僕はなんとなくお作法として `if __name__ = '__main__':` の中に入れています (まちがえて `import` してしまったとしても実行されないように)．`main` 関数 (に相当するもの) を定義して `if __name__ ...` ブロックの中から呼び出す人も多いと思います．

コマンドラインからしか呼び出さない (定義した関数の再利用はしない) ……という前提では `if __name__ ...` ブロックは必要ないのでインデントなしで書いて問題はないかもしれません．

2022-05-18 00:23 UTC, xr0038 commented on tests/dataclass/wl_eff_test.py
> +    assert wl_eff.efficiency[10] == 0.023012329078860527
解決済みっぽいですね．

2022-05-18 00:29 UTC, xr0038 approved these changes
必須ではないですが `Efficiency` に assertion を定義しておくと良いと思います．
追加のリクエストはないので approve にしました．

2022-05-18 00:29 UTC, xr0038 commented on src/telescope_baseline/dataclass/efficiency.py
> +
`wavelength` と `efficiency` のサイズが同じことを期待しているのだと思います． `__post_init__` を定義して以下のように assertion を定義しておくと良いかなと思いました．

``` python
    def __post_init__(self):
        assert self.wavelength.shape == self.efficiency.shape, \
            'wavelength and efficiency should have the same shape'
```

2022-05-18 00:29 UTC, xr0038 commented on src/telescope_baseline/utils/__init__.py
> +__description__ = ''
抜いたのが反映されたのは `dataclass/__init__.py` の方でしょうか？

2022-05-18 00:34 UTC, kataza commented on src/telescope_baseline/dataclass/wl_eff.py
> +        title (str): Title of the data
対応しました

2022-05-18 00:41 UTC, kataza commented on src/telescope_baseline/dataclass/efficiency.py
> +
挿入しました

2022-05-18 00:41 UTC, kataza commented on src/telescope_baseline/utils/__init__.py
> +__description__ = ''
間違えていました。修正しました

2022-05-18 01:24 UTC, tkamizuka reviewed
make*.py に関して、もう少し説明を書いたほうが良い気がしますがいかがでしょうか。また、結構 general な名前なのに対してやっていることは結構ある仮定に基づく限定的なことになっていますが、このネーミングでよいか少し気になりました。

2022-05-18 01:34 UTC, tkamizuka commented on src/telescope_baseline/utils/plot_eff.py
> +fig.savefig(args['-p'],transparent=True)
いつも `if __name__ = '__main__':` が最後に来て「ここが呼ばれるのね」というコードを読んできていたので、現状のように `if __name__ = '__main__':` がコードの途中に埋め込まれているのは見慣れない感じをうけました。確かに間違えではないのですが、可読性の点でも「お作法」に基づいたほうが良いかもしれないと思いました。

インデントは…一段ぐらいなら…という気もしますがいかがでしょう。

2022-05-18 06:18 UTC, HajimeKawahara approved these changes

2022-05-18 06:19 UTC, kataza commented
make*py という名前で json を作成しているようなもの、あるいは別の名前でもプロットを作成しているようなものはほとんどが、「使い捨て」にする（している）コードです。この手のものも共有をうまく機能させるには、名前付けとのルールとか流儀とかがあるといいですね。なんかいいものないでしょうかね、、いままではよく t.py とか plot.py とか、ほんとに使い捨ての名前を使うことが多かったです。

2022-05-19 05:49 UTC, xr0038 approved these changes

2022-05-19 05:53 UTC, tkamizuka commented
make*.py の件、使い捨てコードということで承知しました。
そうなると git で管理するものなのか考えどころがありますが、
とりあえず approve としたいと思います。

2022-05-19 05:56 UTC, tkamizuka approved these changes

2022-05-19 06:17 UTC, xr0038 commented
approve が揃ったので merge します．
// 山田さんの approve が外れていますがこれは僕が設定をいろいろと変えたせいです．

2022-05-19 06:18 UTC, merged