Features/param class
JASMINE-Mission/telescope_baseline pull request #13
Opened 2022-05-10 14:06 UTC by yamadayy

パラメータを保持するクラスを作りました。src/tools/mission/parameters.pyが本体、test/mission/test_mission.pyがテストです。
保持するパラメータの種類がこれで良いか、基本パラメータとそこから計算されるパラメータの識別は妥当か、パラメータのdefault値はこれで良いか、についてご確認をお願いいたします。

2022-05-10 21:22 UTC, xr0038 commented
`src` 直下に `tools` があるのですが，機能を `telescope_baseline` というモジュールの中に実装したいので `tools` を `src/telescope_baseline` 以下 (setup.py でインストールされるスコープ内) に移動させてください．

2022-05-10 21:41 UTC, xr0038 commented
Singleton の挙動についてちょっと確認させてください．期待どおりいくつ作っても同一のインスタンスになっていることは確認したのですが，もしかして新しくインスタンスを生成するたびにパラメタが初期化されているでしょうか？下記は遊んでみて「あれ？」となった例です．

``` ipython
In [1]: from tools.mission.parameters import Parameters
1.703314204859064
5738.8356116745135

In [2]: x = Parameters()

In [3]: y = Parameters()

In [4]: x.aperture_diameter
Out[4]: 0.4

In [5]: y.aperture_diameter
Out[5]: 0.4

In [6]: x.aperture_diameter = 0.2

In [7]: x.aperture_diameter
Out[7]: 0.2

In [8]: y.aperture_diameter
Out[8]: 0.2

In [9]: z = Parameters()

In [10]: z.aperture_diameter
Out[10]: 0.4

In [11]: x.aperture_diameter
Out[11]: 0.4
```

2022-05-11 00:10 UTC, yamadayy commented
モジュールの置き場所の移動は、大澤さんにお願いしても良いでしょうか？

Singletonの挙動チェック有難うございました。大澤さんのご指摘の通り、私が意図した挙動ではありませんでした。別の文書を参照して、書き直しました。どうも、まだ私が__new__と__init__の違いを理解してないようです。コンストラクターは二度目に使うとエラーが出ます。一度目からget_instance関数を呼んでください(テストコード参照)。JavaやC++でSingletonパターンを使う場合は、これが普通です。ただ、この挙動とthread safeにするコードを共有させる方法が分かりませんでした。

2022-05-11 03:24 UTC, xr0038 commented
> モジュールの置き場所の移動は、大澤さんにお願いしても良いでしょうか？

了解です．先ほど push した f0c2fa0 で対処しました．テストの内容もあわせて更新しています．

Singleton の更新ありがとうございます．思っていたとおりの挙動になることを確認しました．引き続き確認を続けます．

2022-05-11 12:40 UTC, HajimeKawahara commented on reqirements.txt
> +numpy~=1.22.3
ファイル名：requirements.txt　じゃないでしょうか？

2022-05-11 12:51 UTC, yamadayy commented
ご指摘ありがとうございます。requirements.txt 名前修正しました。

2022-05-11 23:07 UTC, HajimeKawahara approved these changes, later dismissed
Thank you! I confirmed that the test worked.

2022-05-12 11:18 UTC, xr0038 requested changes
確認しました．コメントは例外で raise するクラスの変更などマイナーなものばかりです．


1 点 Parameters クラスの方針について提案があります．今は変更可能性のあるものは setter を定義していますが，変更する手段を setter ではなくて `set_xxxxx()` という関数で提供するのはどうでしょうか？

> setter が定義されている attribute には代入できる

というルールより

> すべての attribute には代入不可だが `set_xxxx()` という関数がある attribute は変更できる

というルールのほうが目にやさしいかなと思いました．環境に依っては set_[TAB] で補完できるというのも利点です．また，この方針だと将来的に immutable な `dataclass` をつかってコードの簡略化が図れるのではないか……という目算もあります．どうでしょうか？

2022-05-12 11:18 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('diameter value is smaller than inner diameter.')
`Exception` -> `ValueError`
個人の好みではありますがここで inner diameter の値をエラーメッセージに埋め込んでいただけると便利かなと思います．

2022-05-12 11:18 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('inner diameter value is larger than diameter.')
`Exception` -> `ValueError`
こちらも diameter の値をエラーメッセージに埋め込んでいただけると便利かと思います．

2022-05-12 11:18 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('full well electron should be positive.')
`Exception` -> `ValueError`

2022-05-12 11:18 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('Quantum Efficiency should be between 0 and 1.')
`Exception` -> `ValueError`

2022-05-12 11:18 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('Attitude Control Error should be positive.')
`Exception` -> `ValueError`

2022-05-12 11:18 UTC, xr0038 commented on tests/mission/test_mission.py
> +    assert 5738 < sg.orbital_period < 5740
`orbital_height` を 550 km にする処理を入れてから assertion するのはどうでしょうか？

2022-05-12 11:18 UTC, xr0038 commented on tests/mission/test_mission.py
> +    assert 97.5 < math.degrees(sg.inclination) < 97.7
同上です．

2022-05-12 11:18 UTC, xr0038 commented on tests/mission/test_mission.py
> +    assert 0.6869 < sg.total_efficiency < 0.6870
テスト結果がデフォルト値に依存しているので値を fix する行を入れたほうがいいと思います．

2022-05-12 11:18 UTC, xr0038 commented on tests/mission/test_mission.py
> +    assert 0.19999 < two.aperture_diameter < 0.200001
singleton のテストとしては最後にもう一度

``` python
     assert -0.0001 < sg.aperture_diameter - two.aperture_diameter < 0.0001
```

を加えるといいのかなと思いました．

2022-05-12 11:19 UTC, xr0038 commented on src/tools/mission/parameters.py
> +print(one.orbital_period)
これは解決済みです．

2022-05-12 23:00 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception("Singleton Class")
反映しました

2022-05-12 23:00 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('diameter value is smaller than inner diameter.')
反映しました

2022-05-12 23:00 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('inner diameter value is larger than diameter.')
反映しました

2022-05-12 23:00 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('full well electron should be positive.')
反映しました

2022-05-12 23:00 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('Attitude Control Error should be positive.')
反映しました

2022-05-12 23:00 UTC, yamadayy commented on tests/mission/test_mission.py
> +    assert 97.5 < math.degrees(sg.inclination) < 97.7
反映しました

2022-05-12 23:01 UTC, yamadayy commented on tests/mission/test_mission.py
> +    assert 0.19999 < two.aperture_diameter < 0.200001
反映しました

2022-05-12 23:07 UTC, yamadayy commented
大澤さんからのsetterに関する方針の提案は、私は賛成ですが、どのように勧めたらよいでしょう。皆さん同意なら作業してしまいますが。

2022-05-12 23:08 UTC, HajimeKawahara commented
賛成です

2022-05-13 02:19 UTC, yamadayy commented
setterの仕様を変更しました。

2022-05-13 02:53 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +            raise Exception('Quantum Efficiency should be between 0 and 1.')
反映されていることを確認しました

2022-05-13 02:54 UTC, xr0038 commented on tests/mission/test_mission.py
> +    assert 5738 < sg.orbital_period < 5740
確認しました

2022-05-13 02:54 UTC, xr0038 commented on tests/mission/test_mission.py
> +    assert 0.6869 < sg.total_efficiency < 0.6870
こちらも確認しました

2022-05-13 02:58 UTC, xr0038 approved these changes
コードの変更を確認しました．ありがとうございます．

setter の仕様が変わったので対応して `Parameters` のドキュメントをアップデートしていただけると良いと思いますが，ひとまずこれで approve とします．

2022-05-13 06:41 UTC, HajimeKawahara approved these changes

2022-05-13 06:52 UTC, HajimeKawahara commented
これ、誰がマージするんでしたっけ?

2022-05-13 07:03 UTC, yamadayy commented
マージ作業は大澤さんと記憶していたのですが違いましたか？ブランチを作った人がするのかなあ？

2022-05-13 07:41 UTC, xr0038 commented
一応レビュー待ちの状態だと認識していますが…… @kawatadaisuke  @kataza

2022-05-13 07:42 UTC, xr0038 commented
とりいそぎこの PR は ready になったら僕が merge 担当します．

2022-05-16 01:05 UTC, HajimeKawahara commented
approve律速になってますね...

2022-05-16 01:12 UTC, xr0038 commented
> approve 律速

レビューでクオリティを担保するためはしかたない気はしますが……とはいえフリーズしてしまっては意味がないので「忙しいので今回は他の方に託します」みたいな選択肢はあってもいいですね．

2022-05-16 01:14 UTC, yamadayy commented
まだ皆さんやり方に慣れていないので、全部のapproveを待つ必要はないかもしれません。

2022-05-16 01:35 UTC, xr0038 commented
そうですね……むしろほぼ初回だったので

- pull request 画面を開く
- code のタブを開いて更新内容を確認する
- approve を押す

という流れだけでも確認してもらいたかったというのはあるかもしれません．ただ，そのためにこの更新を止めておくというのもおかしな話ですし merge してしまいましょう．

2022-05-16 01:36 UTC, merged