Interp efficiency and weighted mean
JASMINE-Mission/telescope_baseline pull request #22
Opened 2022-05-27 00:00 UTC by HajimeKawahara

I made the linear interpolation function of efficiency and weighted mean.

![efficiency_interp](https://user-images.githubusercontent.com/15956904/170602422-b2987bc2-84f0-4864-8942-3ec72ff001d3.png)

Note:` Efficiency.efficiency` is renamed as `Efficiency.efficiency_grid `and `Efficiency.wavelength` as `Efficiency.efficiency_grid`

2022-05-27 01:01 UTC, kataza approved these changes

2022-05-27 01:10 UTC, xr0038 requested changes
確認しました．ご検討いただければありがたいです．

@kataza さんのリクエストにあった関数は実際の使い方がまだ固まっていないので，とりあえずの実装でいいのかもしれません．打ち合わせで聞いた感じでは `Efficiency` に実装すべき関数なのかちょっと微妙に感じた部分もありますし……．

2022-05-27 01:10 UTC, xr0038 commented on src/telescope_baseline/dataclass/efficiency.py
> +        return np.sum(self.interp(wavelength)*weight)/np.sum(weight)
実装がリクエストされたは与えられた wavelength 点での weighted mean でしたっけ？
区間 $[a, b]$ での重み付き積分だった記憶があるので @kataza さんにご確認をお願いします．

2022-05-27 01:11 UTC, HajimeKawahara commented on tests/dataclass/efficiency_test.py
> +    plt.savefig("efficiency_interp.png")
そうなんですよね。これってどこにつくればいいですかね？

2022-05-27 01:12 UTC, HajimeKawahara commented on src/telescope_baseline/dataclass/efficiency.py
> +        return np.sum(self.interp(wavelength)*weight)/np.sum(weight)
これはもろのリクエストはそうなんですが、結局weightのwavelengthビンが必要なので、このような実装になってしまうと思います。

2022-05-27 01:15 UTC, HajimeKawahara commented on src/telescope_baseline/dataclass/efficiency.py
> +        """compute the interpolated value of efficiency
なるほど。最近[リーダブルコード](https://www.amazon.co.jp/%E3%83%AA%E3%83%BC%E3%83%80%E3%83%96%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%89-%E2%80%95%E3%82%88%E3%82%8A%E8%89%AF%E3%81%84%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E6%9B%B8%E3%81%8F%E3%81%9F%E3%82%81%E3%81%AE%E3%82%B7%E3%83%B3%E3%83%97%E3%83%AB%E3%81%A7%E5%AE%9F%E8%B7%B5%E7%9A%84%E3%81%AA%E3%83%86%E3%82%AF%E3%83%8B%E3%83%83%E3%82%AF-Theory-practice-Boswell/dp/4873115655)よんでるんですが、命名難しいですね。一次補間したものを正式なeffeciencyと定義するならevaluateの方がいいかもしれません。

2022-05-27 01:32 UTC, xr0038 commented on src/telescope_baseline/dataclass/efficiency.py
> +        """compute the interpolated value of efficiency
プログラミングで一番難しいのは命名だと言われていたりしますからね……．
僕は操作よりは機能や目的が陽にわかる名前のほうがいいだろうというスタンスです．

2022-05-27 01:39 UTC, xr0038 commented on src/telescope_baseline/dataclass/efficiency.py
> +        return np.sum(self.interp(wavelength)*weight)/np.sum(weight)
引数に wavelength をとることについては同意します．
weighted mean を `trapz` のような関数で積分から与える必要があるかを確認したいです．

2022-05-27 01:46 UTC, xr0038 commented on tests/dataclass/efficiency_test.py
> +    plt.savefig("efficiency_interp.png")
性質としては examples に近いと思うのですが微妙に毛色が違うのですよね……．

`src/telescope_baseline` 以下にも移動させた方がよさそうなスクリプトがいくつかありますし，ルートに `scripts` とか `snippets` のような名前のディレクトリを作ってそこにまとめて置けるとよいかと思います．

2022-05-27 02:14 UTC, kataza commented on src/telescope_baseline/dataclass/efficiency.py
> +        return np.sum(self.interp(wavelength)*weight)/np.sum(weight)
利用のイメージとしては、PSFを計算するときに波長ごと(たとえば、 1.0, 1.05, 1.1 ミクロン) にPSF を計算し、
これに光子数をかけて(たとえば、1.0-1.025、1.025-1.075、1.075-1.11 ミクロン、最初と最後は途中と波長幅が違う)
加算すれば、ある波長幅(この例だと 1.0 - 1.11 ミクロン) でのPSFが計算できる、というものです。
この光子数を計算するとき、天体のフラックスとかけて使うことをかんがえていたので、効率だけを単独で平均というのはちょっと違うかと思いました。混乱させてすみません。

2022-05-27 02:17 UTC, HajimeKawahara commented on src/telescope_baseline/dataclass/efficiency.py
> +        return np.sum(self.interp(wavelength)*weight)/np.sum(weight)
なるほど。ではまあこれはこれで使うので、片坐さんのご希望のものは使うときに作りましょう。

2022-05-27 12:28 UTC, yamadayy approved these changes

2022-05-27 21:51 UTC, HajimeKawahara commented on src/telescope_baseline/dataclass/efficiency.py
> +        """compute the interpolated value of efficiency
evaluate採用しました

2022-05-27 21:51 UTC, HajimeKawahara commented on tests/dataclass/efficiency_test.py
> +    plt.savefig("efficiency_interp.png")
とりあえずsnippetsつくりました

2022-05-28 09:12 UTC, xr0038 approved these changes

2022-05-28 09:12 UTC, xr0038 commented
Thank you for the updates. I'll merge the PR.

2022-05-28 09:13 UTC, merged