property telescope_throughput returns the mean value calculated in Ef…
JASMINE-Mission/telescope_baseline pull request #25
Opened 2022-06-01 03:53 UTC by yamadayy

…ficiency class.  Also property total_efficiency use this value.
Call Kawahara's weighted mean function in Efficiency class from Parameter class.

2022-06-01 09:48 UTC, xr0038 commented
僕の中では `Parameters` が `Efficiency` の関数を呼ぶというよりは `Parameters` が `Efficiency` インスタンスを直接返してくるイメージだったんですが…… @HajimeKawahara  さんはどうですか？

2022-06-01 10:55 UTC, HajimeKawahara commented on src/telescope_baseline/tools/mission/parameters.py
> +        weight = np.exp(-(wave_ref - 1.2) ** 2.0)
この関数は関数化して、よびだすべきではないでしょうか？
上のベタ打ちの数値も含め....

2022-06-01 10:58 UTC, HajimeKawahara commented on src/telescope_baseline/tools/mission/parameters.py
> +        wave_ref = np.linspace(0.8, 1.6, 1000)
この値は他のパラメタ（波長域など）に依存しないのでしょうか？

2022-06-01 23:51 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +        weight = np.exp(-(wave_ref - 1.2) ** 2.0)
設計の話になるので、実装を進める前に少し議論できませんか？(※1)

2022-06-01 23:51 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +        wave_ref = np.linspace(0.8, 1.6, 1000)
これも※1と同じ。

2022-06-01 23:58 UTC, yamadayy commented
Parameterクラスの機能として何が期待されているのでしょうか。私は、あまり細かい中身を知らない人に簡便に数値を提供するのが役割だと思っていたのですが。その前提で、λ依存性を正確に出すのではなくある種の平均値を返すことにしました。Efficiencyクラスの使い方を知らない人が必要な数値だけを取り出すために、Efficiencyクラスのメソッドに適当なパラメータを入れて出てくる答えを返すことが役割だと考えていました。Facade(入口)の考え方ですが、λ依存性は残した方が良ければのこすことはできますし、平均とλ依存の両方のメソッドを持たせることももちろんできます。Effciencyクラスのインスタンスを返すというのは、Factoryクラスとしての役割を持たせるという考え方になります。いずれにしても、役割を決めれば実装を直すのは簡単なので、そこはやりますが、実装作業に移る前に方向性を決めた方が良いと思います。

2022-06-02 02:29 UTC, HajimeKawahara commented
> 私は、あまり細かい中身を知らない人に簡便に数値を提供するのが役割だと思っていたのですが。その前提で、λ依存性を正確に出すのではなくある種の平均値を返すことにしました。

はい、わたしもそう思っていますが、その場合、単に今定義している波長域
```
　self.__high_wavelength_limit = 1.6e-6  # meter
    self.__low_wavelength_limit = 1.0e-6  # meter
```
間での単純平均（重みを付けずに）にすすべきではないでしょうか？

2022-06-02 07:44 UTC, yamadayy commented
Facadeは内部構造の詳細を知らなくても使える入口をユーザーに提供するもので、河原さんも大澤さんもこの路線は合意されているようなので、その路線でコメントを反映してみます。
一方、内部構造を知っている人は直接内部構造を利用すればよい(Parameterクラスを介さずに)ので、インスタンスを返すという意図がちょっとわかりかねていました。Factoryと言ったのは、Efficiencyクラスを生成する際に渡すパラメータが今後複雑になっても、とにかくdefaultのパラメータを与えて、Efficiencyクラス生成時のパラメータ渡しの手順を知らなくてもインスタンスを取得できる、という意味でした。そちらは、インターフェース一つ作るだけなので、実装自体は問題ないので、やっておきます。が、Efficiencyのインスタンスをいつどこで作るのかは少し悩みどころなので、考えてみます。

2022-06-02 08:50 UTC, yamadayy commented on src/telescope_baseline/tools/mission/parameters.py
> +        weight = np.exp(-(wave_ref - 1.2) ** 2.0)
ベタ打ちの数値はEfficiencyクラスのExamplesのままで、意味がEfficiencyクラスに書かれていないのですが、どういう意味でしょうか。wavelengthはarrayで、短波長リミット、長波長リミット、分点数でnp.linespecを生成している。wegithは、wavelengthと同じサイズのアレイで、Examplesの数値は適当だがここではすべて1を使うべき、という理解で正しいでしょうか。

2022-06-03 00:18 UTC, HajimeKawahara commented on src/telescope_baseline/tools/mission/parameters.py
> +        weight = np.exp(-(wave_ref - 1.2) ** 2.0)
すみません、もし何かのweight関数、ここでは`np.exp(-(wave_ref - 1.2) ** 2.0)` と `np.linspace(0.8, 1.6, 1000)`を使うなら、関数を別定義にして、1.2とか0.8とか1.6は変数+(default値）にするべきかと思ったのですが、そもそも範囲を
```
　self.__high_wavelength_limit = 1.6e-6  # meter
    self.__low_wavelength_limit = 1.0e-6  # meter
```
を用いて単純平均にしたほうが使いやすいという意見です

2022-06-03 01:11 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +        weight = np.exp(-(wave_ref - 1.2) ** 2.0)
> ベタ打ちの数値はEfficiencyクラスのExamplesのままで、意味がEfficiencyクラスに書かれていないのですが、どういう意味でしょうか

Examples に記載されている内容は純粋に引数の与え方の一例を示したもので，JASMINE との関連はないのだと認識しています．

2022-06-03 03:11 UTC, yamadayy commented
直してみましたので、ご確認下さい。

2022-06-04 06:38 UTC, xr0038 requested changes

2022-06-04 06:38 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +print(p.telescope_through_put)
これは確認用の一時的なコードでしょうか？

2022-06-04 06:38 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
>      def telescope_through_put(self):
`through put` よりは `throughput` が適切でしょうか？
efficiency との差別化のために代表値を計算しているという意味が伝わる名称にしたほうがいいかもしれません．

2022-06-04 06:38 UTC, xr0038 commented on src/telescope_baseline/tools/mission/parameters.py
> +        self.__efficiency = Efficiency.from_json(spec_list)
何の efficiency か明確にするために `telescope_efficiency` あるいは `optics_efficiency` にするのはどうでしょうか．

2022-06-04 08:49 UTC, yamadayy commented
コメント反映しました。

2022-06-08 00:55 UTC, merged