Features/pipeline
JASMINE-Mission/telescope_baseline pull request #34
Opened 2022-07-31 07:30 UTC by yamadayy

Implementation pipeline.

2022-07-31 23:20 UTC, xr0038 commented on tests/pipeline/test_analysis.py
> +    w = WCS(naxis=2)
`monkypatch` で乱数を返す関数を固定値を返す関数で上書きしていると理解しました．テストのために乱数の seed を固定するのではうまくいかないのでしょうか？乱数を使っている箇所 (`make_image`) を見ると固定値で置き換えてしまうと，関数の性質が変わってしまうように感じました．

2022-07-31 23:45 UTC, yamadayy commented on tests/pipeline/test_analysis.py
> +    w = WCS(naxis=2)
おっしゃる通り、これがちゃんとしたテストになっているかどうかは甚だ疑問です。ただ、seedを固定するにしても、固定のある程度の長さの乱数列を返す関数に置き換えるにしても、今後ソフトウエアをより現実的にしてゆく過程で乱数を使う箇所が増えるでしょうから、その際に呼ばれる順番が変わって異なる乱数が入ってしまうと、これまでvalidだったものがvalidでなくなる恐れがあります。それはそれで混乱のもとであると考えました。testからvisitorを経由してオブジェクトの中で乱数を呼ぶので、特定の場所の乱数コールだけを固定値にするというのはできるものでしょうか？それができるのであれば、そのように直すのが良いと思いますが。

2022-08-01 01:26 UTC, e-yamane commented on tests/pipeline/test_analysis.py
> +    w = WCS(naxis=2)
単体テストと結合テストの違いのお話をした方が良い気がしますね。

> 関数の性質が変わってしまうように感じました．
> おっしゃる通り、これがちゃんとしたテストになっているかどうかは甚だ疑問です。
この辺りもう少し言語化して欲しいです。

> testからvisitorを経由してオブジェクトの中で乱数を呼ぶ特定の場所の乱数コールだけを固定値にするというのはできるものでしょうか？それができるのであれば、そのように直すのが良いと思いますが。
乱数に限らず、別関数、別モジュールの振る舞い影響を受けずに自らのコードの正当性を確認するなら別関数、別モジュールをMockしても良いのですよ。

業務系のシステムの場合は、別のサービスやDBへのアクセスもMockして単体テスト走らせる事が多いです。

2022-08-04 04:35 UTC, yamadayy commented on tests/pipeline/test_analysis.py
> +    w = WCS(naxis=2)
Zoomで会話した通りです。(私が何か書かないとunresolved conversationが残ってしまうので)

2022-08-04 05:07 UTC, yamadayy commented
Code Climateの警告はすべて解消しました。昨日教えていただいた方法でテストレポートを書いてみましたが、やはりtest coverageがどこで見えるのかわからなかったので、そちらの評価と対応はできていません。
この状況で問題なければ、山根さんapprove、大澤さんmergeお願いいたします。

2022-08-04 05:35 UTC, e-yamane approved these changes
実現したいこと自体把握出来てないので、全部は見切れてませんが、detectorImageのmake_imageについては良い感じに出来てると思います！

2022-08-04 06:29 UTC, xr0038 commented
追加されたコードが多いのと実現したいことのイメージがまだうまく理解できていないのでもう少しお待ちください……

2022-08-04 06:51 UTC, yamadayy commented
大澤さん、了解です。Visitorパターンの解説私どこかに書いてslackにあげたと思うのですが、もしVisitorにあまりなじみがなければ、そこを見てもらわないとコードが分かりにくいと思います。

2022-08-04 07:03 UTC, xr0038 commented
Slack で該当の文章を見つけました (JASMINE-C2-TN-YY-024_Python_Visitor)．
まずは目を通してみます．

2022-08-15 00:15 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/astrometriccatalogue.py
> +def fit_astrometry(parameter, t, lon, lat):
これは fitting の目的関数でしょうか？ `fit_astrometry` という名称は confusing かなと思いました．

2022-08-15 00:22 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/astrometriccatalogue.py
> +def fit_astrometry(parameter, t, lon, lat):
はい、fitting目的の関数です。名前は考えます。
以前Zoomでお話しした通り、山根さんと相談して設計を大幅に変更しています。pipeline_v2というフォルダーを作って、テストもtests2の下に入れていますが、うまく動くようになったらpipelineとtestsに移すなどの操作をした上で、マージをお願いしようと思っています。
このブランチのマージは少し待ってください。

2022-08-15 00:23 UTC, xr0038 commented on tests2/test_pipeline.py
> +    return file
file path を扱う場合はライブラリ (pathlib?) を使ったほうがよさそうです．
また，テスト用のデータは `src` 以下に置かないほうがいいかなと思います．

2022-08-15 00:28 UTC, xr0038 commented on tests2/test_pipeline.py
> +    assert(a != None)
ファイルが `tests2` にある = テストはしないという意図で良いでしょうか？

2022-08-15 00:28 UTC, xr0038 commented on tests2/test_fits_storage.py
> +    assert(di != None)
ファイルが `tests2` にある = テストはしないという意図で良いでしょうか？

2022-08-15 00:30 UTC, yamadayy commented on tests2/test_pipeline.py
> +    return file
はい、どこが適切ですかね？

2022-08-15 00:30 UTC, e-yamane commented on tests2/test_fits_storage.py
> +    assert(di != None)
これは、私が答えます。tests2を作っているのは、特定のテストクラスを単独で走らせる方法の調査をサボりたかったので、他のテストを走らせることでRed-Green-Refactoringのサイクルが長くなるのを避けるために対象のテストだけ切り出していました。後々testsに統合するイメージです。

2022-08-15 00:31 UTC, yamadayy commented on tests2/test_fits_storage.py
> +    assert(di != None)
いえ、作業中にほかの時間がかかるテストのために待たされたくないので、一時的にtest2に置いています。いろいろ動作が確認できたら、testに移します。

2022-08-15 00:43 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/astrometriccatalogue.py
> +def fit_astrometry(parameter, t, lon, lat):
> このブランチのマージは少し待ってください

了解しました！
眺めていたら v2 が生まれていたので「あれ？」と思ったところでした．

2022-08-15 00:45 UTC, xr0038 commented on tests2/test_pipeline.py
> +    return file
うーむ……おそらく他の場所では使用しなそうですし `tests` ディレクトリの下に置くのが適切だと思います．

2022-08-15 00:46 UTC, xr0038 commented on tests2/test_fits_storage.py
> +    assert(di != None)
後に統合予定ということで了解しました．
上の conversation と合わせて resolved とします．

2022-08-15 00:46 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline/astrometriccatalogue.py
> +def fit_astrometry(parameter, t, lon, lat):
> このブランチのマージは少し待ってください。
私は詳しくなかったのでプルリク名に「[WIP]」って付けてわかるようにしてましたが、
この手のプルリクは、Draft Pull Requestにすると良いかもしれませんね。

https://www.publickey1.jp/blog/19/githubwippull_requestdraft_pull_request.html

2022-08-15 00:50 UTC, xr0038 commented
まだ作業中ということでしたら一度 draft PR に設定変更していただけるとステータスがわかりやすいかもしれません．
…… draft PR でも Code Climate はチェックしてくれる設定になっていたはずです．

2022-08-15 00:56 UTC, yamadayy commented
混乱させて済みませんでした。draftに変更しておきました。

2022-08-29 08:33 UTC, e-yamane reviewed
astrometric_catalogueと、astrometric_catalogue_builderとcatalogue_entry
を一旦見てみました。
多分、構造似てるので似通った指摘が続くことが想定されるので一度ここまでのコメントの是非についてご検討いただけますか？

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +            print(row)
printはなくして欲しいです。pythonってロギング機能的なのあるんでしたっけ？

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +                                               frame='icrs'), float(row[7])))
saveとloadで処理が非対称なのが気になります。
非対称となっているので、例えば、pm_raと、pm_ra_cosdecが逆変換となっており、知識が流出してます。
難しければ構いませんが、なんとか出来るなら対応いただけるといいなって感じです。

なお、saveとloadが非対称であるが故に、あるAstrometricCatalogueオブジェクトxがあるとして、
x.save('a.csv')
y = AstrometricCatalogue.load('a.csv')
で、xとyが等価であるかが判断付きにくいです。

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +        parameter: array for [lon0, lat0, pm_lon_coslat, pm_lat, para]
これ、クラスの方が良くないですか？
また、クラスにするのが難しいならarrayよりもtuppleと表現した方が良いかなと思いました。
個人的な感覚かもですが、arrayは、同種のデータが複数あるイメージがあります。
異種のデータをひとまとめにしていると言う意志を強調するならtuppleの方が良い気がします

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +        ty.append(t[i].jyear)
添え字でくるくる回すより、

```
for x in t  # xは適切な名前付けて下さい
        ls.append(get_sun(x).geocentricmeanecliptic.lon.rad)
        ty.append(x.jyear)
```
の方が良い気がします。

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +        residual[i] = (lon[i] - lont[i]) ** 2 + (lat[i] - latt[i]) ** 2
lontとlattはresidualを計算するための一時退避用の変数っぽいので、配列にする必要は無く、
for分の中で回して良いのでは無いかと思います。

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +class AstrometricCatalogueBuilder:
状態持たないなら、変換処理自体はstaticmethodで良いのでは無いですかね？
（その他のBuilderも同様なら同様のご検討を下さい。以降同じコメントはしません）

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            parameter = [np.radians(266), np.radians(-5), 0., 0., np.radians(1 / 3600)]
これ、値に変化無いのでループの外で定義してもいいと思います

2022-08-29 08:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            latdata, londata, t = self._time_seriese_of_individual_star(otsp, s)
position_on_the_skyってどれくらいデータ量ありそうですか？
何気にえげつない回数ループ回るので、最初のループでidだけ取り出すのでは無く、
idをキーにして同一idを持つposition_on_the_skyのlistを持つような辞書を作った方が良いと思いました。

仮にn個position_on_the_skyがあって、idがすべてバラバラだとすると、ここのループは
n + n ** 2
ループが回ると思います。

_add_individual_observationまで考慮するともっと回るかな？すいません。検証できてませんw
とにかくデータが少ないなら良いですが多いのであればベラボーに増えそうだというのが感想です。

2022-08-29 09:08 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +            print(row)
済みません。debug用のものが残ってました。grepしましたが、printはここ以外は例外のところだけです。loggingは考えないといけませんね。

2022-08-29 09:11 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +                                               frame='icrs'), float(row[7])))
CatalogueEntryのほうで、本来pm_ra_cosdecとするべきところがpm_raとなっていたので、こちらを修正しました。非対称というのは、引数の順番でしょうか。パラメータの順番をそろえました。

2022-08-29 09:17 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +        parameter: array for [lon0, lat0, pm_lon_coslat, pm_lat, para]
scipy.optimize.leastsqを呼び出しているので、parameterがnumpy.ndarrayであることは仕様なのです。関数をclass methodでかけるかどうかは試していませんが、クラスにするとしてもクラスの初期化に依存しないようにするとすればstatic methodになるので、とりあえずこのまま放置させてください。

2022-08-29 09:20 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +        ty.append(t[i].jyear)
はい、修正します。

2022-08-29 09:22 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +        residual[i] = (lon[i] - lont[i]) ** 2 + (lat[i] - latt[i]) ** 2
はい、修正します。

2022-08-29 09:25 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +class AstrometricCatalogueBuilder:
はい、修正します。

2022-08-29 09:27 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            parameter = [np.radians(266), np.radians(-5), 0., 0., np.radians(1 / 3600)]
本来はs毎に適切な初期値を計算して入れないといけないところをさぼっているので、TODOをつけました。

2022-08-29 09:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            latdata, londata, t = self._time_seriese_of_individual_star(otsp, s)
10万程度になります。これも、どう最適化するとよいのかすぐには思いつかないので、TODOをつけてそのままで進めたいです。

2022-08-29 11:05 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +        parameter: array for [lon0, lat0, pm_lon_coslat, pm_lat, para]
了解です！

2022-08-29 11:05 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +            print(row)
ありがとうございます！

2022-08-29 11:17 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +                                               frame='icrs'), float(row[7])))
> 非対称というのは、引数の順番でしょうか
例えば、save処理がこうなってますが、
```
write.writerow([e.stellar_id, e.ra, e.dec, e.pm_ra_cosdec, e.pm_dec, e.distance, e.coord.obstime, e.mag])
```
であれば、対を成すloadは、
```
tmp.append(CatalogueEntry(
        stellar_id=int(row[0]),
        ra = float(row[1]),
        dec = float(row[2]),
        pm_ra_cosdec = float(row[3]),
        pm_dec = float(row[4])
        distance=float(row[5])
        obstime=row[6]
        float(row[7]))
```
こうなってると、いいなという感じですね。
SkyCoordのプロパティとCatalogueEntryのプロパティの関係式はCatalogueEntryに属する知識なのでCatalogueEntryにカプセル化したいという意図です。

逆を言えば、CatalogueEntryのコンストラクタがIDとSkyCoordを受け取るのであれば、
IDと、SkyCoordを作成するためのプロパティをwriteするのが良いのかも知れません。

どちらが適切かはわかりません。

2022-08-29 11:19 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            parameter = [np.radians(266), np.radians(-5), 0., 0., np.radians(1 / 3600)]
了解です

2022-08-29 11:21 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            latdata, londata, t = self._time_seriese_of_individual_star(otsp, s)
from_on_the_sky_positionのテストありますか？
あるなら私の方でコード書いてみますが。

2022-08-29 12:36 UTC, e-yamane reviewed
第２弾です

2022-08-29 12:36 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_builder.py
> +            self._generate_a_stellar_image(a, dp, s)  # index s is needed here
_generate_a_stellar_imageを見てもdpを配列で、sをdpのindexとして渡す必要性がわかりませんでした。
_generate_a_stellar_imageの中でサボってる処理があって、その時に必要だと言うことであれば、_generate_a_stellar_imageにもtodoコメント付けてくれると助かります。

2022-08-29 12:36 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
使い勝手的には、saveとloadが逆の方が使いやすい気がします。
つまり、saveの時はfolderが無ければ作って保存、loadの時はfolderが無ければ、読み込み対象が無いので例外。

こっちの方が作りにくいですけどね。

現行のままだとするなら、せめてエラーはNotADirectoryErrorの方が良いと思います。
保存しようとしてるのにFileNotFoundErrorは受け取り側がちょっと「？？？」ってなる気がします。

2022-08-29 12:36 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/map_on_detector.py
> +    def get_sky_positions(self):
あれ？MapOnDetectorがPositionOnDetector -> MapOnDetector の変換ルール知ってるのはNGなのでは？
それぞれの変換はXXXXBuilderが担うのでは？

2022-08-29 12:36 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/pipeline.py
> +class Pipeline:
pipelineはsimulationとanalysisはクラス分割しても良いかもしれませんね。
Pipelineのコンストラクタ引数ってsimulation処理でしか使ってませんよね。
analysisだけしたい人から「？？？」ってなりそう

2022-08-29 12:36 UTC, e-yamane commented on tests/pipeline/test_catalogue_entry.py
> +    assert(abs(c.pm_ra * u.yr / u.mas - 351) < 1)
浮動小数点の誤差を気にしてるテストならpytest.approxを使うと良いかもしれません。Hw_coeff_test.pyで利用してます

2022-08-31 04:08 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +                                               frame='icrs'), float(row[7])))
修正してみましたので、ご確認ください。

2022-08-31 04:09 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            latdata, londata, t = self._time_seriese_of_individual_star(otsp, s)
test_astrometric_catalogue_builder.pyの中に、test_from_on_the_sky_positionがあります。

2022-08-31 04:16 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/detector_image_builder.py
> +            self._generate_a_stellar_image(a, dp, s)  # index s is needed here
おっしゃる通りでした。extract methodで分離したmethodの中身を精査すべきでした。直しました。

2022-08-31 05:45 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
修正してみましたが、saveの側のテストをどう書くか迷って、TODOにしてしまいました。

2022-08-31 06:49 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/map_on_detector.py
> +    def get_sky_positions(self):
ご指摘の通りです。MapOnTheSkyBuilderに移しました。まだ少し汚い。

2022-08-31 06:54 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/pipeline.py
> +class Pipeline:
分離しました

2022-08-31 06:57 UTC, yamadayy commented on tests/pipeline/test_catalogue_entry.py
> +    assert(abs(c.pm_ra * u.yr / u.mas - 351) < 1)
testsのほうは今後使わない予定なので、放置させてください。

2022-09-01 06:57 UTC, e-yamane commented on tests/pipeline/test_catalogue_entry.py
> +    assert(abs(c.pm_ra * u.yr / u.mas - 351) < 1)
了解です

2022-09-02 00:25 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            latdata, londata, t = self._time_seriese_of_individual_star(otsp, s)
プルリクで、別案書いてみました。

https://github.com/JASMINE-Mission/telescope_baseline/pull/57
ただ、それ以前にoptimize.leastsqがとても時間が掛かるようで、これの呼び出し回数が減らないと誤差っぽい気がします。（データ量が増えるとそうでもないかもですが...）
もし、今の方が読みやすいと判断されるのであれば今のままでも良いかもしれません。

https://github.com/JASMINE-Mission/telescope_baseline/pull/57

2022-09-02 00:33 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_builder.py
> +            self._generate_a_stellar_image(a, dp, s)  # index s is needed here
ありがとうございます

2022-09-02 00:37 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/map_on_detector.py
> +    def get_sky_positions(self):
ありがとうございます。MapOnTheSkyBuilderは必要あれば別途コメントします

2022-09-02 00:39 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/pipeline.py
> +class Pipeline:
ありがとうございます

2022-09-02 01:56 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +                                               frame='icrs'), float(row[7])))
ん〜悩ましいですねぇ。saveとloadが対称にはなったのですが、肝心のドメインロジック、
例えばCatalogueEntry.pm_ra_cosdecが、SkyCoord.icrs.pm_ra_cosdec * u.yr / u.mas
であると言うことが漏れ出てこのドメイン知識が３箇所に現れてきてるんですよね。

ここ、csvフォーマットって決まってるんでしたっけ？
ここって SkyCoord -> CatalogueEntry と言う関数従属性があるので、
もし、フォーマットに制約が無く、JSMINEオリジナルフォーマットで良いなら
CSVに出力するデータは、CatalogueEntryのプロパティを保存するという意識を止めて、
SkyCoordのプロパティを出力するのが良いかも知れません。

ここかなりややこしい話してるかも知れません。コメントでやりとりするのは難しそうなのでどこかで話しましょうか？

2022-09-02 03:17 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue.py
> +                                               frame='icrs'), float(row[7])))
コメントありがとうございます。フォーマットは決まってないです。今日午後はあいていますので、ご都合が良い時間帯をご指定下さい。いつものパーソナルミーティングでお待ちしております。https://kyoto-u-edu.zoom.us/j/7838600940?pwd=S09EOVhETWZkblNKTEprdWNxNTVMUT09

2022-09-02 06:17 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
ぱっと思いつく物はあるので、私の方で書き足してみましょうかね？
書き足した後に見てもらって、ここのコメントはresolveにしようかと思います。

2022-09-02 07:17 UTC, e-yamane reviewed
第３弾コメント。

2022-09-02 07:17 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/map_on_detector_builder.py
> +                raise ValueError
折角なので例外のメッセージとして送出した方が良いと思います。
printだと処理の流れで原因を取りこぼしそうなのと、出来ればprintは実コードからは撲滅したいので

2022-09-02 07:17 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
ここは、indexがファイル名と連動してるので、添え字でのforループがいいかと

2022-09-02 07:17 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/map_on_the_sky.py
> +    def __init__(self, positions_on_the_sky: list[PositionOnTheSky] = [], orbit_id: int = -1):
ココだけじゃ無いかも知れないですが、ここidっぽい変数が後ろにあるのはこのオブジェクトのIDじゃないんですかね？このオブジェクトを一意に識別する目的の物であれば、selfの後ろに定義してあって欲しいです。
ちなみに、引数の順番変更はリファクタリングツールの「Change Signature」で安全に行う事が出来ます

2022-09-02 07:17 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/simulation.py
> +        self.__folder = 'tmp'
この手のオブジェクトプロパティをコンストラクタ内で固定かするとテストしにくかったりするので、コンストラクタ引数のデフォルト値とした方がいい気がしますね。特にここはフォルダ名ですし、、、

2022-09-02 07:17 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/simulation.py
> +            Path(self.__folder).mkdir()
ここは、無視して頂いても構いませんが、本来的にはエラーハンドリングがいろいろ面倒なので、ディレクトリ生成は、parents=True（対称ディレクトリの親ディレクトリが無くてもたどって作ってくれる）とexist_ok=True(対称ディレクトリが既に存在してもエラーにはしない)は常に付けといても良いかもしれません。
この２つは普通にプログラム組んでて付けてて駄目なケースはほぼ思いつきません。

2022-09-03 08:03 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +            latdata, londata, t = self._time_seriese_of_individual_star(otsp, s)
#57をマージしました。

2022-09-03 08:26 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/map_on_detector_builder.py
> +                raise ValueError
例外メッセージに変更しました。

2022-09-03 08:34 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
変更しました。

2022-09-04 05:40 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/map_on_the_sky.py
> +    def __init__(self, positions_on_the_sky: list[PositionOnTheSky] = [], orbit_id: int = -1):
修正しました。

2022-09-04 05:57 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/simulation.py
> +        self.__folder = 'tmp'
変更しました。

2022-09-04 06:11 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/simulation.py
> +            Path(self.__folder).mkdir()
直しました。

2022-09-04 07:25 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
テスト書き足してみました。問題無ければこのコメントは解決済みにします

2022-09-05 06:18 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
Slackでいろいろやりとりしたので解決済みとしますね

2022-09-05 06:19 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/detector_image_catalogue.py
> +            i += 1
ありがとうございます！

2022-09-05 06:20 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/map_on_the_sky.py
> +    def __init__(self, positions_on_the_sky: list[PositionOnTheSky] = [], orbit_id: int = -1):
ありがとうございます

2022-09-05 06:20 UTC, e-yamane commented on src/telescope_baseline/tools/pipeline_v2/simulation.py
> +            Path(self.__folder).mkdir()
ありがとうございます！！

2022-09-05 15:32 UTC, yamadayy commented on tests2/test_detector_image.py
> +def di():
change name

2022-09-05 15:32 UTC, yamadayy commented on tests2/test_map_on_the_sky_builder.py
> +def sc():
change name

2022-09-05 15:33 UTC, yamadayy commented on tests2/test_position_on_detector.py
> +def test_pos():
divide test method.

2022-09-05 15:33 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/astrometric_catalogue_builder.py
> +    @staticmethod
remove one blank line.

2022-09-05 15:33 UTC, yamadayy commented on tests2/test_astrometric_catalogue_builder.py
> +def test_from_on_the_sky_position():
Add a blank line.

2022-09-05 15:34 UTC, yamadayy commented on tests2/test_astrometric_catalogue_builder.py
> +
remove it.

2022-09-05 15:34 UTC, yamadayy commented on tests2/test_detector_image_catalogue.py
> +        path = Path(dname, 'fits')  #
remove it.

2022-09-05 15:34 UTC, yamadayy commented on tests2/test_map_on_detector_builder.py
> +@pytest.fixture
Add a blank line

2022-09-05 15:34 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline_v2/map_on_detector_builder.py
> +    def _store_list_of_detector_position(self, sky_positions, tmp):
extract method.

2022-09-05 15:35 UTC, yamadayy commented on tests2/test_map_on_the_sky.py
> +def test_save(mos):
divide method.

2022-09-05 15:36 UTC, yamadayy commented on tests2/test_map_on_detector.py
> +    m = MapOnDetector([PositionOnDetector(1, Position2D(0.0, 0.0), Time('2000-01-01 00:00:00'), 12.5),])
Remove unnecessary comma.

2022-09-05 15:36 UTC, yamadayy commented on tests2/test_map_on_the_sky.py
> +def test_load():
divide method.

2022-09-05 15:36 UTC, yamadayy commented on tests2/test_position_on_the_sky.py
> +def test_pos():
divide method

2022-09-05 15:36 UTC, yamadayy commented on tests2/test_astrometric_catalogue.py
> +def test_save():
divide method

2022-09-05 15:36 UTC, yamadayy commented on tests2/test_astrometric_catalogue.py
> +def test_load():
divide method

2022-09-05 15:36 UTC, yamadayy commented on tests2/test_detector_image_builder.py
> +def test_from_stellar_image():
divide method

2022-09-05 15:37 UTC, yamadayy commented on tests2/test_astrometric_catalogue_builder.py
> +def test_from_on_the_sky_position():
divide method

2022-09-05 15:37 UTC, yamadayy commented on tests2/test_map_on_detector.py
> +def test_get_sky_positions(mod):
divide method

2022-09-05 15:37 UTC, yamadayy commented on tests2/test_map_on_detector.py
> +def test_save(mod):
divide method

2022-09-05 15:37 UTC, yamadayy commented on tests2/test_map_on_detector.py
> +def test_load():
divide method

2022-09-05 15:37 UTC, yamadayy commented on tests2/test_map_on_the_sky.py
> +def test_load2(position_on_the_sky):
divide method

2022-09-05 15:37 UTC, yamadayy commented on tests2/test_map_on_detector.py
> +def test_save(csv_read):
divide method

2022-09-05 15:37 UTC, yamadayy commented on tests2/test_map_on_the_sky.py
> +def test_save2(file):
divide method

2022-09-06 01:02 UTC, yamadayy commented
レビューお願いいたします。

2022-09-06 01:13 UTC, yamadayy commented
Unresolved conversationのうち、山根さんコメントは山根さんがapproveしてくださったので私の方でresolve conversationとしておきました。一件残っているのは大澤さんのコメントですが、osではなくpathlibを使うようにというコメントで、対応済みです。これをresolveしていただければ、mergeできるようになると思います。

2022-09-18 08:18 UTC, xr0038 requested changes
……長らくお待たせいたしました！一通り目を通したつもりです．同じコメントが複数あったり言っていることが食い違ったりしているかもしれません……変なことを言っていたらご指摘ください．

細かな typo など，すぐに対応できそうな箇所を直していただければと思います．おそらく最近クラス名の変更があったのではないかと思いますが，コメントや関数名が追従していないような箇所がいくつか見受けられました．

また，現在の実装では `DetectorImage` はフルサイズの画像という理解でいいでしょうか？ simulation の最終生成物 (analysis の始点) は 9×9 の切り出し画像であるべきではないでしょうか？

情報を保持するクラスの大まかな構成はこれでいいと思いますが，細かい部分はいろいろとアップデートが必要だと感じました．また，現在の実装では各 builder にシミュレーションと解析両方の関数が実装されていますが，実際には大きく異なる問題を扱うのでベースとなるクラス (共有情報) を継承しつつ，別のクラスとして実装したほうがいいのではないかと思います．

個人的な感想ですが for-loop 等でスコープが限られているところはともかく，関数の引数などで 1,2 文字の変数を使われるとレビューする側として結構厳しいなと感じました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue.py
> +                                e.coord.distance / u.pc, e.coord.obstime, e.mag])
`* u.yr / u.mas` 等は無次元化しているという理解であっていますか？こうしたケースでは `to_value()` method を使うほうが安全かと思います．

- https://docs.astropy.org/en/stable/units/quantity.html

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue.py
> +                                e.coord.distance / u.pc, e.coord.obstime, e.mag])
ついでにちょっと確認です．`AstrometricCatalog` には観測時刻が必須なのでしたっけ？ある epoch の (ra, dec, v_ra_cosdec, v_dec, parallax) が記録されており，観測時刻 (と軌道情報) が定義されて `PositionOnTheSky` に変換されるのだと思って資料を読んでいたので少し引っかかりました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        """Build DetectorImage from StellarImage class
名称と説明が一致していないような気がするのでご確認をお願いします．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
これは `mag` が photon 数を意味しているのでしたっけ？

magnitude の意味を考えると misleading なので `CatalogueEntry` に magnitude → photon 数を計算する method を実装しておいたほうがいいと思います．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
この PR で修正は求めませんがこの実装だと以下のような問題があると思います．

- photon の Poisson ノイズが考慮されていない
- 明るい星に対して極端にパフォーマンスが落ちる

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +    """Builder class for Stellarimage class
説明が過去の名称を引きずっているでしょうか．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +            c: DtectorImageCatalogue
s/DtectorImageCatalogue/DetectorImageCatalogue/

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/data/a.csv
> +1,266.4049882865447,-28.936177761791473,-3.325090692327255,13.745681936077188,1.0,2000-01-01 00:00:00.000,12.5
テスト用のファイルではありますがファイル名を再考してほしいです．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_pipeline.py
> +    assert(b is not None)
異常時に `None` が返ってくる実装になっていないと思います．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_pipeline.py
> +    assert(a is not None)
異常時に `None` が返ってくる実装になっていないように思います．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +    def from_on_tye_sky_position(self, o: MapOnTheSky, wl: list[WCSwId]) -> list[MapOnDetector]:
s/from_on_tye_sky_position/from_on_the_sky_position/

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/data/detector.csv
> +1,0.0,0.0,12.5,2000-01-01 00:00:00
カラム名 (ヘッダー行) を加えませんか？

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/data/a.csv
> +1,266.4049882865447,-28.936177761791473,-3.325090692327255,13.745681936077188,1.0,2000-01-01 00:00:00.000,12.5
冗長かもしれませんがカラム名があったほうがいいと思いました．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/data/detector.csv
> +1,0.0,0.0,12.5,2000-01-01 00:00:00
あー…… `sky.csv` では 1 行目だけ例外 (orbit id) として扱う実装をしているのですね．
consistency がとれないのでヘッダは要らないと思い直しました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/wcswid.py
> +class WCSwId:
orbit & exposure と望遠鏡の指向方向を結びつける object という理解でいいでしょうか？
ちょっと名前と機能に隔たりがあるように思いました (修正依頼ではないです)．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_detector_image.py
> +    assert detector_image is not None
失敗したときに `load` 関数は `None` を返さないように思います．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_pipeline.py
> +    tests_dir = 'tests/pipeline'    # change it when test dir move
`Path.cwd()` で返ってくる値としてはどのようなケースを想定しているのでしょうか．

ある決まったディレクトリから実行しないと正しいファイルパスが取得できない実装になっているでしょうか？実際にはルート以外で実行するケースはほとんどないと思いますが少し気になりました．

'tests/pipeline' 以下で作業をするのでしたら，このファイル (`test_pipeline.py`) の場所を取得して相対パスを作成するという手続きにしたほうが安心かもしれないと思いました．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_pipeline.py
> +            tmp_path.mkdir()
ファイル名を取得する関数が (temporary とはいえ) ディレクトリを作成する機能を持つことには違和感があります．一時ファイル or 一時ディレクトリを作成する機能は別の関数として実装しませんか．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_pipeline.py
> +            tmp_path.mkdir()
一時ファイル作成機能は消すところまで実装したいですがテストと連携させる方法は調査の必要がありそうですね．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_map_on_detector.py
> +    return next(iter(f))
ファイルシステムまで含めたテストが必要ということでなければ IO stream を使用すると一時ファイルを作成せずに済むかもしれません．

- https://docs.python.org/3/library/io.html

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/data/a.csv
> +1,266.4049882865447,-28.936177761791473,-3.325090692327255,13.745681936077188,1.0,2000-01-01 00:00:00.000,12.5
カラム名については `sky.csv` との consistency を考えて不要だと思い直しました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        """
PSF を用いた測定をしているので get よりも重たい単語を使いたいと思いました．

説明の Calculate image center position は何を測っているのかが不明瞭なので書き直したほうが良さそうです．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +                PositionOnDetector(1, Position2D(s.center[0], s.center[1]), Time('2000-01-01 00:00:00.0'), mag=3000))
exposure ID, 時刻は画像データ (DetectorImage) に含まれている (あとはとってくるだけ) という想定だと認識しましたが正しいでしょうか．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        # TODO need to implement cross-match
PositionOnDetector には天体を特定するための情報が含まれていない設計になっていると思いますが，この段階で天体の同定 (cross match) が必要になるという想定でしょうか？

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/position_on_detector.py
> +    def __init__(self, exposure_id: int, p: Position2D, datetime: Time, mag: float = 12.5):
`mag` のデフォルト値は必須でしょうか？
設定する場合も「有り得そうな値」は避けておいたほうが無難かもしれません．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/position_on_detector.py
> +    """Data class for detector position of individual image.
個々の画像 (検出器) における天体の位置を保存するクラスではないでしたっけ？
この説明ではちょっと誤解を生むような気がします．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/detector_image.py
> +        self.__hdu.writeto(filename, overwrite=True)
`overwrite` は `True` をベタ書きせずオプションで設定できるようにしてください．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +    def _generate_a_stellar_image(self, a, dps):
"星像を作る関数" は個々の星に対応するオブジェクトに持たせたほうがいいような気がします．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        """
大きい画像から位置測定までがひとつの関数で実行されていますが，機上での操作と地上での操作が両方含まれているので分割したいです．現在の設計に加えて 9×9 の切り抜き画像というデータクラスがあったほうがいいと思います．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue.py
> +    """
等級があるのでパラメタの数は 5 ではないような……

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/simulation.py
> +        """
別の場所でもコメントしましたが等級を含んでいるので `AstrometricCatalogue` のパラメタ数は 6 ではないでしょうか．また `pixel number` よりは画像サイズ (検出器サイズ？) と説明してほしいです．

return するのは `DetectorImageCatalogue` ではなくてその List ですね．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/simulation.py
> +    def __init__(self, t: list[Time] = [], w_list: list[WCSwId] = [], folder: str = 'tmp'):
ここのデフォルト値って必要でしょうか？後から時刻やポインティングリストを編集することはなさそうな気がします．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        residual[i] = (lon[i] - lont) ** 2 + (lat[i] - latt) ** 2
ここはベクトル演算で書いたほうがいいと思います．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        ty.append(time.jyear)
また `get_sun(time)` も時刻のアレイを引数にとれるはずなので for-loop 回さなくてもできるはずです．また，`astropy.time.Time` は複数の時刻をアレイとして持つことができたと思います．その実装を使うとユリウス日等への変換も loop を回さずに済みます．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        return AstrometricCatalogue(result)
`staticmethod` で `A.from_...` というメソッドを実行した場合には返り値が `A` であることを期待してしまう気がします．今回は `AstrometricCatalogBuilder.from_on_the_sky_position` という名前のメソッドが `AstrometricCatalog` を返すので引っかかりを感じました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/analysis.py
> +        dic_list.append(DetectorImageCatalogue(di))
見慣れない条件が出てきて戸惑ったのですが，これは軌道周回ごとにデータを整理しているという認識で正しいでしょうか？実際には各画像に軌道 ID が振られておりそれで分類するという実装になるのですかねぇ……．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/analysis.py
> +        """
現時点では仕方ないのだと思いますが `wcs` (ポインティング情報) が `Analysis` の入力にあるのはちょっと引っかかりました．現在の構成なら `MapOnDetectorBuilder` が生成する役割を担うと思います．`window_size` も本来であればダウンリンクされたデータから自然に決まる値なので引数にはならないと思います (解析としては運用中に変わってもいい)．

データ設計次第ですが望遠鏡の指向方向 (暫定値) などのメタ情報は fits ファイルのヘッダから読み取ることになるのかなと思っています．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/simulation.py
> +            di[j].hdu.writeto(str(fpathname), overwrite=True)
経験的に `overwrite` のデフォルトを `True` にするのはやめたほうがいいと思います．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_astrometric_catalogue_builder.py
> +    a2 = builder.from_on_the_sky_position(o)
この関数の挙動をテストするためには星を複数個含むデータを使用するべきかなと思いました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/wcswid.py
> +        """
`orbit_id` は周回ごとに変わる通し番号で，`exposure_id` は周回内でカウントアップする通し番号という理解でよいでしょうか？

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/simulation.py
> +    def _generate_one_hdu(self, dib, o, sib, wl):
`_generate_one_hdu` という関数が `len(wl)` 個のファイルを生成するのはあまり良い naming ではないと思いました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +        """
リファクタリング中に修正しそこねた関数名でしょうか？

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +            ret.append(PositionOnTheSky(position.exposure_id, sky, position.mag, position.datetime))
**To Do** であることは理解しますが，暫定的な処置であっても "それっぽいもの" が入っていると混乱するので stellar ID であるところに exposure ID を入れるのはやめてください．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/wcswid.py
> +        """
他のところを見ているとそうではないような感じがしますね……撮像のたびに (衛星の位置が変わるたびに) `orbit_id` も変わるという認識で正しいでしょうか？

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +    def get_sky_positions(self, mod: MapOnDetector):
実際には同じ周回内の `List[MapOnDetector]` をまとめて処理をすることになると思います．軌道周回ごとのデータをまとめるクラスがあったほうが良さそうに思いました．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +    pm_lat = coord.barycentricmeanecliptic.pm_lat.value * 4.848136e-9
`astropy.Quantity` を使用しているのであれば単位変換は `to.("target unit")` でできると思います．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_pipeline.py
> +        DetectorImage.load(str(get_tests_file_name('tmp9_0.fits')))
テスト用のデータも役割がわかるように命名してください．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_map_on_detector_builder.py
> +    f_name = str(get_tests_file_name('tmp.fits'))
テスト用のデータも機能がわかるように命名してください．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_detector_image.py
> +    return DetectorImage.load(get_tests_file_name('tmp0_0.fits'))
テスト用のデータも役割がわかるように命名してください．

2022-09-18 08:18 UTC, astronasutarou commented on tests/pipeline/test_map_on_detector_builder.py
> +    detector_image = DetectorImage.load(get_tests_file_name('tmp0_0.fits'))
テスト用のデータも役割がわかるように命名してください．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        peaks_tbl = find_peaks(data, threshold=200.)
`threshold` はベタ書きせず引数で与えるようにしてください．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        half_size = (window_size - 1) / 2
`window_size` が奇整数であることが前提になっていたりしますか？

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        e_psf_builder = EPSFBuilder(oversampling=4, maxiters=3, progress_bar=True)
このあたりのパラメタも関数の引数として設定できるようにしてください．

2022-09-18 08:18 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/catalog_entry.py
> +        return self.__coord.distance / u.pc
単位なしの数値にしたい場合は `.to_value("target unit")` メソッドを使うのが安全です (以下同様)．

2022-09-18 08:18 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        self.__ny = ny
nx = NAXIS1, ny = NAXIS2 という理解でいいでしょうか？
その場合，現在の実装では x, y が逆になる箇所がいくつかあります．

2022-09-18 08:18 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        self.__ny = ny
`nx`, `ny` よりは FITS の定義に寄せて  NAXIS1, NAXIS2 に近い名称 (例えば `naxis1`, `naxis2`) にしたほうが誤解がないかもしれません．

2022-09-18 08:18 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        a = np.random.uniform(0.0, 10.0, (self.__nx, self.__ny))
`nx`, `ny` の定義にも依りますが `(self.__ny, self.__nx)` が正しいと思います．

2022-09-18 08:18 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +                a[xp][yp] += 1
FITS 画像の (NAXIS1, NAXIS2) = (nax1, nax2) にアクセスするためには `data[nax2][nax1]` となります．x, y を flip させると混乱するので，個人的には画像では `x`, `y` を使用せず以下のように書いたほうがわかりやすいかなと思いました．

``` python
nx1 = int(self.__psf_w * np.random.randn() + dps.x + 0.5)
nx2 = int(self.__psf_w * np.random.randn() + dps.y + 0.5)
if 0 <= nx1 < self.__naxis1 and 0 <= nx2 < self.__naxis2:  # 属性の方も名称を変更しています
    a[naxis2][naxis1] += 1
```

2022-09-18 08:18 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        a = np.random.uniform(0.0, 10.0, (self.__nx, self.__ny))
手元で実行した結果です．

``` python
import numpy as np
import astropy.io.fits as fits

data = np.zeros((10, 50))
hdu = fits.PrimaryHDU(data=data)
hdu.data.shape
--->
  (10, 50)
hdu.header
--->
  SIMPLE  =                    T / conforms to FITS standard                      
  BITPIX  =                  -64 / array data type                                
  NAXIS   =                    2 / number of array dimensions                     
  NAXIS1  =                   50                                                  
  NAXIS2  =                   10                                                  
  EXTEND  =                    T                                                  
```

2022-09-18 09:20 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue.py
> +                                e.coord.distance / u.pc, e.coord.obstime, e.mag])
to_value()知りませんでした。修正します。AstrometricCatlogueに時刻が入っているのは、時刻が無いとpositionがどの時点のposition だかわからないからです。proper motionで動くので。ですので、PositionOnTheSkyと同じ意味の時刻ではありませんが、時刻が必要です。良いネーミングがあれば提案してください。

2022-09-18 09:21 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        """Build DetectorImage from StellarImage class
修正します。

2022-09-18 09:27 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue.py
> +                                e.coord.distance / u.pc, e.coord.obstime, e.mag])
> 時刻が無いとpositionがどの時点のposition だかわからないからです。proper motionで動くので。

状況を理解しました．カタログでは epoch が共通であるということを想定していたので，個別の天体に対して時刻を設定していることに引っかかったのでした．csv として保存している現状ではこの実装でいいと思います．

2022-09-18 09:41 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
済みません。現実装ではmagに光子数を入れてしまっています。この変換を考えるのは、いろんなパラメータに依存して面倒なので、後回しにさせてください。とりあえず、magを返すだけのget_nphotonを作ってかぶせておいて、TODOをつけました。
明るい星のパフォーマンスはご指摘の通りです。xp, ypの計算に乱数を使っているので、Poiossonノイズは自然に入ると考えています。

2022-09-18 09:42 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +    """Builder class for Stellarimage class
修正します。

2022-09-18 09:44 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +            c: DtectorImageCatalogue
修正します。

2022-09-18 09:46 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
> Poiossonノイズは自然に入ると考えています。

もし勘違いをしていたら申しわけないのですが，乱数によって位置が変わるので pixel 単位でのカウントはばらつきますが総 photon 数が保存しているので (特に暗い側で) 統計がおかしくなるような気がします．

2022-09-18 09:48 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        e_psf_builder = EPSFBuilder(oversampling=4, maxiters=3, progress_bar=True)
修正しました。(commitすると、引数の数が多すぎるエラーが出ると思いますが)

2022-09-18 09:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        self.__ny = ny
アレイサイズをarray[nx][ny]としていて、FITSにこれを渡すと、naxis1=ny, naxis2 = nxとなると思います。アレイの扱いを基準にしたつもりですが、問題があれば、今後設計議論をさせてください。取りあえずこのままで。

2022-09-18 09:52 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        a = np.random.uniform(0.0, 10.0, (self.__nx, self.__ny))
はい、逆になることは認識しています。これを変更しようとすると全体を見ないといけないので、設計議論後でお願いします。

2022-09-18 09:52 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +                a[xp][yp] += 1
同上

2022-09-18 10:59 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
私の理解は、乱数が確率分布で与えられている、したがって、あるセルに光子が入る確率pはこの分布で表されている。そこにN個の光子がばらまかれる、したがって、実際にセルに光子が入るか入らないかはPoisson過程で、これで数えられる光子数はPoisson誤差を入れたものになっている、です。確率分布は無限に遠いところまで見ているので、総photon数が一定であることは悪いことをしないと思うのですが(星像Windowに入る数もPoisson誤差が入っているはず)、何か勘違いしていますでしょうか？

2022-09-18 11:04 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        e_psf_builder = EPSFBuilder(oversampling=4, maxiters=3, progress_bar=True)
Code climateがエラーを出すので、progress_barは引数から外しました。

2022-09-18 11:07 UTC, yamadayy commented
座標をFITSに合わせるかどうかは保留しています。magから光子数への変換はちゃんとした実装は保留していますが、関数としては変換関数を作りました(magをそのまま返すだけですが)。上の二つは、ちょっと設計の議論をさせてください。変数名は気が付く範囲で直しました。map_on_detector_builderのget_positions_on_detector関数に引数を増やす件は、codeclimateエラーが出ない範囲で対応しました。

2022-09-18 11:27 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
> 確率分布は無限に遠いところまで見ているので、総photon数が一定であることは悪いことをしないと思うのですが

とりあえず測光したときの photon noise がほぼゼロになるので現実を反映していないような……．

N が大きいときに各ピクセルのカウントは近似的に Poissson 過程に従うとは思うのですが，ピクセル間に相関が生まれてしまっているので和をとった後の結果が統計的に歪むのだと思います．上で挙げた測光もそうですが中心位置推定にも影響がありそうに思いました．

2022-09-18 11:55 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
論点理解しました。空間分布としてPoissonノイズが十分入っているはずだから大丈夫だと思っていましたが、時間軸側でも光子総数n個に対するPoisson分布があるから、総数が固定ではいけないというご指摘ですね。そんな気がしてきました。総数nはもっと大きな数Nに対する確率pがあって、n=Npで決まるはずなのですが、Nが何なのか、pが何なのかがしっくり来ていませんが、とりあえず総数を√Nで揺らがせて与えることにします。

2022-09-19 01:12 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/catalog_entry.py
> +        return self.__coord.distance / u.pc
修正しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +    def _generate_a_stellar_image(self, a, dps):
そのようなオブジェクトが今は無いので、次の課題とさせてください。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +    def from_on_tye_sky_position(self, o: MapOnTheSky, wl: list[WCSwId]) -> list[MapOnDetector]:
修正しました

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        peaks_tbl = find_peaks(data, threshold=200.)
パラメータ数が4を超えるので、TODOにしました。いくつかのパラメータをクラス(C++なら構造体でも良いのだけど)にまとめる必要があり、設計変更になります。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        half_size = (window_size - 1) / 2
はい、前提にしています。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        # TODO need to implement cross-match
どこにクロスマッチを入れるかはもう少し考えさえてください。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +                PositionOnDetector(1, Position2D(s.center[0], s.center[1]), Time('2000-01-01 00:00:00.0'), mag=3000))
はい。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +    pm_lat = coord.barycentricmeanecliptic.pm_lat.value * 4.848136e-9
ありがとうございます。修正しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +    def get_sky_positions(self, mod: MapOnDetector):
クラスの定義は、どういうまとまりかわからないけどまとまりということだけで、どうまとめるかはまとめる側の問題として処理する、ではだめでしょうか。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +            ret.append(PositionOnTheSky(position.exposure_id, sky, position.mag, position.datetime))
修正しました

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +        """
修正しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/position_on_detector.py
> +    """Data class for detector position of individual image.
修正してみました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/position_on_detector.py
> +    def __init__(self, exposure_id: int, p: Position2D, datetime: Time, mag: float = 12.5):
消しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/simulation.py
> +    def __init__(self, t: list[Time] = [], w_list: list[WCSwId] = [], folder: str = 'tmp'):
フォルダー名以外はdefault値を消しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/simulation.py
> +        """
修正しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/simulation.py
> +    def _generate_one_hdu(self, dib, o, sib, wl):
修正しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/simulation.py
> +            di[j].hdu.writeto(str(fpathname), overwrite=True)
修正しました。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/wcswid.py
> +class WCSwId:
考えておきます。

2022-09-19 02:31 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/wcswid.py
> +        """
orbit_idは周回ごと、exposure_idは撮像ごとの通し番号です。exposure_idは周回内だけでなく、周回をまたいでどんどんカウウントアップすることを想定しています。テストでは、一周回で一撮像しかしていないので、分かりにくいですね。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/data/a.csv
> +1,266.4049882865447,-28.936177761791473,-3.325090692327255,13.745681936077188,1.0,2000-01-01 00:00:00.000,12.5
ファイル名を変更しました。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_astrometric_catalogue_builder.py
> +    a2 = builder.from_on_the_sky_position(o)
今後の課題としてください。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_detector_image.py
> +    assert detector_image is not None
修正しました。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_map_on_detector.py
> +    return next(iter(f))
次の課題としてください。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +    assert(b is not None)
今後の課題として、テストを追加します。とりあえず、これはオブジェクトを作ったらOK、作ったオブジェクトが異常でもOKというテストです。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +    tests_dir = 'tests/pipeline'    # change it when test dir move
pycharmで実行するとtests/pipelineで、github actionで実行するとsrcで、手動で実行する場合は普通はトップディレクトリーになると思います。その違いを吸収しようとしています。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +            tmp_path.mkdir()
調査後、ということでお願いします。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +        DetectorImage.load(str(get_tests_file_name('tmp9_0.fits')))
この一連の指摘は、後日対応とさせてください。いくつかは勝手にresolveしています。

2022-09-19 02:31 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +    assert(a is not None)
simulationのテストと同様、簡易テストです。あとで考えます。

2022-09-19 03:36 UTC, e-yamane commented on tests/pipeline/test_pipeline.py
> +    tests_dir = 'tests/pipeline'    # change it when test dir move
ここは、私も気になってましたが、pipelineが長期生存していて、actionsの進化に追いついてないんですよね。
ここは、developにマージ後に私の方でシンプルにしようと思ってました。
＃コメント足しとけば良かったなぁ...

ちなみに、
> pycharmで実行するとtests/pipeline
これ本当ですか？
IntelliJとかでJavaのテスト実行するときってカレントディレクトリはプロジェクトルートなイメージありますが、、、

2022-09-19 05:54 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
`numpy.random.poisson` を使ってください．

2022-09-19 05:57 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/catalog_entry.py
> +        return self.__coord.distance / u.pc
`distance`, `pm_ra_cosdec`, `pm_dec` の修正もお願いします．

2022-09-19 05:57 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        self.__ny = ny
とりあえずこのままということで了解しました．

2022-09-19 06:03 UTC, xr0038 commented on tests/pipeline/test_pipeline.py
> +    assert(b is not None)
……すみません．僕のコメントがまったく指示になっていませんでした．

`assert(b is not None)` と書くと `c.do()` の返り値が `None` ではないことが正常だという表明になります．現在の実装ではそうなっていません．混乱を生むので assert 文は削除してください．

2022-09-19 06:03 UTC, xr0038 commented on tests/pipeline/test_pipeline.py
> +    assert(a is not None)
……すみません．僕のコメントがまったく指示になっていませんでした．

`assert(b is not None)` と書くと `c.do()` の返り値が `None` ではないことが正常だという表明になります．現在の実装ではそうなっていません．混乱を生むので assert 文は削除してください．

2022-09-19 06:10 UTC, xr0038 commented on tests/pipeline/test_pipeline.py
> +    tests_dir = 'tests/pipeline'    # change it when test dir move
ちなみに僕のローカル環境ではルートディレクトリの名前が `telescope_baseline` ではなく `baseline` になっているために正常に動きませんでした．想定外のケースですね．

まあ GitHub actions で動いているのでこのコメントは close します．

2022-09-19 06:13 UTC, xr0038 commented on tests/pipeline/test_pipeline.py
> +            tmp_path.mkdir()
了解しました．

2022-09-19 06:14 UTC, xr0038 commented on tests/pipeline/test_map_on_detector.py
> +    return next(iter(f))
了解しました．

2022-09-19 06:14 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        # TODO need to implement cross-match
了解しました．

2022-09-19 06:15 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +    def _generate_a_stellar_image(self, a, dps):
了解しました．

2022-09-19 06:19 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/simulation.py
> +            di[j].hdu.writeto(str(fpathname), overwrite=True)
修正を確認しました．

2022-09-19 06:23 UTC, xr0038 commented on tests/pipeline/test_astrometric_catalogue_builder.py
> +    a2 = builder.from_on_the_sky_position(o)
せめてもうひとつ用意しませんか？さほど時間がかかる作業ではないと思います．

`AstrometricCatalogueBuilder` のコアとなる機能に星を stellar ID で分類する関数がありますが，星が複数あることではじめてその機能のテストになると思うので……．

2022-09-19 06:27 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +        """
`from_astrometric_catalogue_2_list` の 2 は必要でしょうか．

2022-09-19 06:40 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
修正しました。

2022-09-19 06:41 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +            ret.append(PositionOnTheSky(position.exposure_id, sky, position.mag, position.datetime))
確認させてください．更新されたコードでは `stellar_id = position.exposure_id` として名前を付け替えていますが，現在のコードでは `position.exposure_id` を代入しないと動かない状態になっているのでしょうか．仮に何か問題が発生したときに情報の伝達が切れていたほうが良いと思うのですが，固定値ではダメなのでしたっけ？

暫定的であったとしても意味があるコードを書かれると何らかの表明に見えてしまいます．今回のケースではさほど問題にならないと思いますが「ID を ID に渡している」という状況は一見まともに見えかねないのですごく嫌な臭いがするのです．

2022-09-19 06:42 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/catalog_entry.py
> +        return self.__coord.distance / u.pc
済みません。確認忘れです。修正しました。

2022-09-19 06:44 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +    def get_sky_positions(self, mod: MapOnDetector):
"まとまり" に機能をもたせたくなるかどうか……ですかね．
なんとなく必要になるかなと思いましたが実際にやってみないとわからないですね．

2022-09-19 06:44 UTC, xr0038 commented on tests/pipeline/test_pipeline.py
> +        DetectorImage.load(str(get_tests_file_name('tmp9_0.fits')))
了解しました．

2022-09-19 06:46 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +    pm_lat = coord.barycentricmeanecliptic.pm_lat.value * 4.848136e-9
確認しました．
// 数値が欲しいだけなので `to_value("target unit")` を使うようコメントした方が良かったですね……

2022-09-19 06:47 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +    tests_dir = 'tests/pipeline'    # change it when test dir move
プロジェクトルートをとる方法もあるみたいなので、次のチケットで考えてみます。

2022-09-19 06:50 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +    assert(b is not None)
修正しました。

2022-09-19 06:51 UTC, yamadayy commented on tests/pipeline/test_pipeline.py
> +    assert(a is not None)
修正しました

2022-09-19 06:52 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        peaks_tbl = find_peaks(data, threshold=200.)
TODO ということで了解しました．

これをクラスにまとめて引数にするかと言われると微妙ですね…… Builder の attribute として与えたほうがスッキリする気がします．Code Climate の引数の制限は結構厳しいので調整するか，一部の関数では wontfix 宣言をして引数の超過を許容しても良いんじゃないかなと思います．

2022-09-19 06:54 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        half_size = (window_size - 1) / 2
重箱の隅をつつくようですがどこかに assertion を書いておきませんか？

2022-09-19 06:54 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        """
切り抜きクラスの作成については次の課題とさせてください。説明の書き直しはしました。getでないとすると、estimate暗いでしょうか？

2022-09-19 07:09 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image.py
> +        self.__hdu.writeto(filename, overwrite=True)
修正しました。

2022-09-19 07:09 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue.py
> +    """
コメント修正しました。

2022-09-19 07:16 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
修正を確認しました．

Poisson distribution の range は正整数なので負値チェックはなくても大丈夫です．手元で調べたら返り値の型も整数だったのでキャストも不要かもしれません．

とりいそぎ close します．

2022-09-19 07:21 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        """
感覚に依るところが大きそうですがぱっと思いついたのは estimate とか measure とかでしょうか……．

説明の書き換えを確認しました．個人的な意見ですが `stellar window` と `image center position` が何を指しているのか分かりにくいので，他にコメントを見直す機会があれば再考をお願いします．

2022-09-19 07:23 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +    def estimate_positions_on_detector(self, detector_image: DetectorImage, window_size: int, oversampling=4, maxiters=3)\
解決済み

2022-09-19 08:48 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/detector_image_builder.py
> +        for k in range(int(dps.mag)):
修正しました。

2022-09-19 10:02 UTC, yamadayy commented
これまでにいただいたコメントは、すべて確認して、修正、あるいは保留などコメントしました。

2022-09-19 10:36 UTC, xr0038 commented
僕の画面では Unresolved conversations が 9 件 (うち 4 件は対応いただいたものに対する追確認) 残っているのですが山田さんの方では確認できませんか？

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_detector_builder.py
> +        half_size = (window_size - 1) / 2
assertを置きました。

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +        """
外します。

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/map_on_the_sky_builder.py
> +            ret.append(PositionOnTheSky(position.exposure_id, sky, position.mag, position.datetime))
暫定で1を入れます。

2022-09-19 11:51 UTC, yamadayy commented on tests/pipeline/test_astrometric_catalogue_builder.py
> +    a2 = builder.from_on_the_sky_position(o)
上でのIDの代入のところで暫定で1を入れていてIDの付け方を今後の課題にしています。ですので、2つでもここを解決しないといけないので、これは今後の課題とさせてもらえないでしょうか。

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/analysis.py
> +        """
はい、ご指摘の通りです。TODOで書いておきます。

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/analysis.py
> +        dic_list.append(DetectorImageCatalogue(di))
はい、そうです。

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        return AstrometricCatalogue(result)
xxBuilderはxxを作るためのクラスという位置づけですので、ABuilderがAを返すのは設計通りです。ABuilderを返してはいけません。(ということでご指摘の答えになっているでしょうか？)

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        ty.append(time.jyear)
少し格闘したのですが、うまくいきませんでした。あとで調べますが、取りあえずこのままでお願いします。

2022-09-19 11:51 UTC, yamadayy commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        residual[i] = (lon[i] - lont) ** 2 + (lat[i] - latt) ** 2
スカラーが絡んでいるので、どうやるのかすぐに調べられませんでした。(できませんと書いている記事もある)。保留させてください。

2022-09-19 11:55 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        residual[i] = (lon[i] - lont) ** 2 + (lat[i] - latt) ** 2
了解しました．

2022-09-19 11:55 UTC, astronasutarou commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        ty.append(time.jyear)
今後検討ということで了解しました．

2022-09-19 11:55 UTC, yamadayy commented
済みませんでした。見落としてました。保留も含めてコメントを返しました。

2022-09-19 12:03 UTC, xr0038 commented on src/telescope_baseline/tools/pipeline/astrometric_catalogue_builder.py
> +        return AstrometricCatalogue(result)
すみません！ `@classmethod` と勘違いをして的はずれなコメントをしていました．

個人的には `build` や `generate` みたいな動詞が欲しくなりましたが Builder クラスが build するのは当然なので要らないのですかね．resolved にします．

2022-09-19 12:14 UTC, xr0038 commented on tests/pipeline/test_astrometric_catalogue_builder.py
> +    a2 = builder.from_on_the_sky_position(o)
`AstrometricCatalogBuilder` の単体テストであれば ID の問題には引っかからないと思ったのですが，何か見落としがあるでしょうか？試しに手元で同じデータを Stellar ID = 2 として入れてみましたが想定した挙動をしていました．

参考までに patch を書いておきます．

``` patch
--- a/tests/pipeline/test_astrometric_catalogue_builder.py
+++ b/tests/pipeline/test_astrometric_catalogue_builder.py
@@ -26,10 +26,19 @@ def test_from_on_the_sky_position1():
         s = PositionOnTheSky(1, SkyCoord(lon=londata[i], lat=latdata[i], unit=('rad', 'rad'),
                                          frame='barycentricmeanecliptic'), 3000, t[i])
         o.append(MapOnTheSky(positions_on_the_sky=[s]))
+    for i in range(len(t)):
+        s = PositionOnTheSky(2, SkyCoord(lon=londata[i], lat=latdata[i], unit=('rad', 'rad'),
+                                         frame='barycentricmeanecliptic'), 3000, t[i])
+        o.append(MapOnTheSky(positions_on_the_sky=[s]))
     a2 = builder.from_on_the_sky_position(o)
 
-    coord = a2.get_catalogue()[0]
+    coord = a2.get_catalogue()
+
     # TODO: need to fix proper motion check. Windows and Linux give different answer.
-    assert 4.657 < coord[0][0] < 4.658
-    assert -0.1 < coord[0][1] < -0.09
-    assert 4.8e-6 < coord[0][4] < 4.9e-6
+    assert 4.657 < coord[0][0][0] < 4.658
+    assert -0.1 < coord[0][0][1] < -0.09
+    assert 4.8e-6 < coord[0][0][4] < 4.9e-6
+
+    assert 4.657 < coord[1][0][0] < 4.658
+    assert -0.1 < coord[1][0][1] < -0.09
+    assert 4.8e-6 < coord[1][0][4] < 4.9e-6
```

2022-09-19 12:31 UTC, yamadayy commented on tests/pipeline/test_astrometric_catalogue_builder.py
> +    a2 = builder.from_on_the_sky_position(o)
MapOnTheSkyのID付け問題と関係ないということで了解しました。修正します。

2022-09-20 05:10 UTC, xr0038 commented on tests/pipeline/test_astrometric_catalogue_builder.py
> +    a2 = builder.from_on_the_sky_position(o)
テストのアップデートを確認しました．

2022-09-20 05:11 UTC, xr0038 approved these changes
コメントがすべて対応されたことを確認しました．ありがとうございます．

2022-09-20 05:14 UTC, merged