update A_lambda in hwc_colors.py
JASMINE-Mission/telescope_baseline pull request #41
Opened 2022-08-08 04:03 UTC by koheimiyakawajp

updated "A_lambda ()" as Yano-san instructed,
and the old one was moved to "A_lambda_linear ()" in hwc_colors.py.

2022-08-08 07:21 UTC, xr0038 commented
ありがとうございます．
とりいそぎ以下のコマンドでフォーマットを整えたものを追い push します．

``` console
$ autopep8 -i --select E225,E226,E227,E231,E261,E265,E271,E302,E303,E502 src/telescope_baseline/hw_band_coeff/hwc_colors.py 
```

2022-08-08 07:46 UTC, xr0038 commented
ちょっと状況を整理させてください．

今回の PR でファイル `hwc_colors.py` を追加していますが，もともとの目的は `Hw_coeff.py` の関数 (`A_lambda`) を更新することだと聞いていたような気がします．特に強い理由がなければ `Hw_coeff.py` をアップデートするのが良いと思います．

2022-08-08 12:01 UTC, koheimiyakawajp commented
申し訳ありません。私のローカルにあるコードとごちゃまぜにしてしまっていました。。
Hw_coeff.pyの方のアップデートで対応します。

2022-08-08 12:27 UTC, koheimiyakawajp commented
Hw_coeff.pyのアップデートで対応しました。
また、先に上げた不要ファイル(hwc_colors.py)は削除しました。
よろしくお願い致します。

2022-08-09 09:53 UTC, xr0038 approved these changes
ありがとうございます！コードの更新を確認しました．

2022-08-09 09:54 UTC, xr0038 commented
ありゃ？ conflict がありますね．

2022-08-09 09:57 UTC, xr0038 commented
online editor で conflict を解決しました

2022-08-09 09:59 UTC, xr0038 commented
あれ？僕が編集したせいでテスト落ちていますかね……確認します．

2022-08-09 10:06 UTC, xr0038 commented
うーむ…… `feature/Hw_fix` のルートとなっている commit がちょっと古かったのでしょうか？ `develop` から同期をかけたときにこのブランチにいろいろと降ってきましたね．

2022-08-09 10:11 UTC, xr0038 requested changes
すみません．extinction law を変えたので計算結果が変わります．計算結果と対応させているテストで引っかかるようになっているようです．新しい `A_lambda` の計算でテストが通るようにテスト内容を確認していただけないでしょうか (テストの書き方を見直すべきだとは思うのですがとりあえず今回はこれでお願いします)．

2022-08-09 11:05 UTC, koheimiyakawajp commented
テスト内容も合わせてアップデートしました。

2022-08-10 00:32 UTC, xr0038 approved these changes
更新を確認しました．ありがとうございます！

2022-08-10 00:32 UTC, merged